Added te.po - Telugu Translation
Jeffser/Alpaca pull request #320
Opened 2024-09-21 14:11 UTC by SpaciousCoder78

2024-09-21 16:40 UTC, olumolu requested changes

2024-09-21 16:40 UTC, olumolu commented on po/te.po
> +msgstr "డిలీట్/స్టాప్ మోడల్ బటన్‌ల రూపాన్ని మార్చారు"
Add space / before and after

2024-09-21 16:42 UTC, olumolu commented on po/te.po
> +msgstr "కొన్ని కారణాల వల్ల \"'S\"ని కలిగి ఉన్న స్థిర జనరేట్ శీర్షికలు"
\"'S\"_ space needed \"'S\"ని

2024-09-21 16:46 UTC, SpaciousCoder78 commented on po/te.po
> +msgstr "డిలీట్/స్టాప్ మోడల్ బటన్‌ల రూపాన్ని మార్చారు"
Fixed

2024-09-21 16:46 UTC, SpaciousCoder78 commented on po/te.po
> +msgstr "కొన్ని కారణాల వల్ల \"'S\"ని కలిగి ఉన్న స్థిర జనరేట్ శీర్షికలు"
Fixed

2024-09-21 16:47 UTC, SpaciousCoder78 commented
Updated the translation with suggested changes

2024-09-21 16:49 UTC, olumolu commented on po/te.po
> +msgstr "ఒల్లామా v0.3.0కి నవీకరించబడింది (కొత్త మోడల్‌లు)"
Space missing v0.3.0కి

2024-09-21 21:01 UTC, merged

2024-09-21 21:01 UTC, Jeffser commented
That's fine, thanks for your contribution!

2024-09-22 03:05 UTC, SpaciousCoder78 commented
Welcome